name: E2E test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  tests_e2e:
    name: Run end-to-end tests
    runs-on: ubuntu-latest
    steps:
      - uses: Kesin11/actions-timeline@v2
      - uses: actions/checkout@v5
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - uses: actions/setup-node@v6
        with:
          node-version-file: ".node-version"
      - name: Install dependencies
        run: bun install
      - name: Install playwright browsers
        run: npx playwright install --with-deps
      - name: Run tests
        run: npx playwright test
